# Generated by Django 3.2.25 on 2024-06-02 20:39

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=myapp.models.generate_event_id, max_length=9, unique=True),
        ),
    ]
