# Generated by Django 3.2.25 on 2024-06-02 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
