# Generated by Django 3.2.25 on 2024-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='myapp/files/marketplace_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='myapp/files/reward_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/files/profile_pics'),
        ),
    ]
