# Generated by Django 5.0.6 on 2024-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_eventparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='eventparticipants',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='eventparticipants',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
