# Generated by Django 5.0.6 on 2024-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_eventparticipants_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
