# Generated by Django 5.0.6 on 2024-06-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_eventparticipants_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipants',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventparticipants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.event'),
        ),
    ]
