# Generated by Django 5.0.6 on 2024-06-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_eventparticipants_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventparticipants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event'),
        ),
    ]
