# Generated by Django 5.0.6 on 2024-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_eventparticipants_id_alter_eventparticipants_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
