# Generated by Django 3.2.25 on 2024-06-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=150)),
                ('event_name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('cleanup', 'Environmental Clean-up'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('planting', 'Tree Planting'), ('recycling', 'Recycling / Composting'), ('other', 'Other')], max_length=50)),
                ('event_location', models.CharField(max_length=150)),
            ],
        ),
    ]
