# Generated by Django 3.2.25 on 2024-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_image_alter_rewards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rewards'),
        ),
    ]
