# Generated by Django 3.2.25 on 2024-07-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_rewards_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='points',
        ),
    ]
