# Generated by Django 3.2.25 on 2024-07-24 08:22

from django.db import migrations

def create_default_thread(apps, schema_editor):
    Thread = apps.get_model('myapp', 'Thread')
    default_thread = Thread.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_thread'),
    ]

    operations = [
        migrations.RunPython(create_default_thread),
    ]
