# Generated by Django 3.2.25 on 2024-07-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_event_is_closed'),
        ('myapp', '0008_event_email'),
    ]

    operations = [
    ]
